# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# English (default language)
en:
  languageCode: en-us
  contentDir: content/en
  title: Jake and Megan's Wedding
  params:
    description: A beautiful wedding at the Chateau

# French
fr:
  languageCode: fr-fr
  contentDir: content/fr
  title: Le Mariage de Jake et Megan
  params:
    description: Un beau mariage au Château
  menu:
    main:
      - name: Accueil
        url: /#top
        weight: 10
      - name: Événements
        url: /#events
        weight: 20
      - name: Contact
        url: /#contact
        weight: 30
