# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# English (default language)
en:
  languageCode: en-us
  contentDir: content/en
  title: Chateau Buno
  params:
    description: Event Venue in France

# French
fr:
  languageCode: fr-fr
  contentDir: content/fr
  title: Chateau Buno
  params:
    description: Venue de mariage en France
  menu:
    main:
      - name: Accueil
        url: /#top
        weight: 10
      - name: Événements
        url: /#events
        weight: 20
      - name: Réservation
        url: /#booking
        weight: 30
      - name: Galerie
        url: /#gallery
        weight: 40
